### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by bastianx** [deflomu/moneymoney-mintos-extension#11]
v1.6 message:
Mintos.lua:203: attempt to index field 'data' (a nil value)

**Comment by deflomu** [comment]
It looks like it cannot find the entry for your investments. Do you maybe not have any investments yet? The extension should handle that correctly but I don't know what the response from mintos looks like if there are no investments.

Could you check the protocol (⌘ + L) for the response that mintos sends you? There should be a line like this: `1> Sending: POST https://www.mintos.com/en/my-investments/list` and after that there should be the response which triggers the error.

Please remove any sensitive informations from the response before posting here.

**Comment by bastianx** [comment]
```
1> Sending: GET https://www.mintos.com/en/login/twofactor
          1> Received: <!DOCTYPE html> <html class="en" lang="en" prefix="og: http://ogp.me/ns#"> <head><script> ---info removed---
          1> Lade Kontostand und Umsätze für Mintos Available Funds ...
          1> Getting transactions since xx.xx.2018...
          1> Sending: POST https://www.mintos.com/en/my-investments/list
          1> Sending: GET https://www.mintos.com/en/login
          1> Received: <!DOCTYPE html> <html class="en" lang="en" prefix="og: http://ogp.me/ns#"> <head><script> ---info removed---
          1> Mintos.lua:203: attempt to index field 'data' (a nil value)
```

Is this helpful?
I do have investments.

**Comment by roNn23** [comment]
It's not working for me, also. Checked the code and found some issues. The `twoFactorCode` in `sendTwoFactorCode` is not correct, because you pass `code`. Also I have to `return` `loginWithPassword` and `sendTwoFactorCode` in `InitializeSession2`. But after that, it's not working anyway. The server redirects me to /login whether the code is correct or not. Did check all request variables drölf-times. :/

**Comment by tcurdt** [comment]
Broken for me as well :-(

**Comment by deflomu** [comment]
Could you test the current master-version? I hope I fixed the 2FA problem there

**Comment by tcurdt** [comment]
I am currently getting this with master:
![Screen Shot 2019-08-11 at 19 57 39](https://user-images.githubusercontent.com/13697/62837680-664b1100-bc72-11e9-93de-f3aaa978bcd3.png)

**Comment by tcurdt** [comment]
That said: All my other extensions seem to have a signature like this appended. This is missing for the Mintos extension.
```
-- SIGNATURE: MC0CFBgWT4P4sUhi+ADL9x5vOEPY/2nHAhUAgRZcKuxmcpnHTI42B1Di6Mp9hVk=
```

**Comment by deflomu** [comment]
To test the development version (now not in master but here https://github.com/deflomu/moneymoney-mintos-extension/blob/issue-11-2fa/Mintos.lua ) you need a [beta](https://moneymoney-app.com/beta/) version of moneymoney and you need to disable signature checking
<img width="518" alt="Screenshot 2019-08-11 20 16 53" src="https://user-images.githubusercontent.com/100795/62837913-76182480-bc75-11e9-873d-8cd3ec95b02c.png">

If the fix is working I will release a new signed version of the extension

**Comment by tcurdt** [comment]
Ah, OK - that's why the option is not there :)
Not sure I really want to switch to the beta to try though :-/

But where is the place to download the signed releases then?
The ones from github are all without the signature. I checked at least 1.2, 1.6 and 1.7.

**Comment by deflomu** [comment]
I released a new signed version. Can you test if it works? https://github.com/deflomu/moneymoney-mintos-extension/releases/tag/v1.8

**Comment by tcurdt** [comment]
Awesome! Works! Thanks!
